# Generated by Django 5.1.4 on 2026-06-16 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementScolarite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('type_periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('semestriel', 'Semestriel'), ('exoneration', 'Exonération')], max_length=12, verbose_name='Type de période')),
                ('periode_couverte', models.CharField(help_text='Ex : 2025-11 (mois) ou 2025-S1 (semestre).', max_length=7, verbose_name='Période couverte')),
                ('montant', models.BigIntegerField(help_text='> 0, sauf exonération où 0 est autorisé.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (centimes FCFA)')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='valide', max_length=10, verbose_name='Statut')),
                ('caissier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaissements', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='etudiants.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Paiement de scolarité',
                'verbose_name_plural': 'Paiements de scolarité',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['etudiant'], name='scolarite_p_etudian_b97653_idx'), models.Index(fields=['periode_couverte'], name='scolarite_p_periode_bfb750_idx')],
            },
        ),
    ]
