# Generated by Django 5.1.4 on 2026-06-16 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('terminaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('uid', models.CharField(max_length=20, verbose_name='UID scanné')),
                ('type_scan', models.CharField(choices=[('identification', 'Identification'), ('debit', 'Débit'), ('credit', 'Crédit'), ('controle', 'Contrôle')], default='identification', max_length=15)),
                ('nonce', models.CharField(max_length=64, unique=True, verbose_name='Nonce')),
                ('horodatage_carte', models.BigIntegerField(help_text='Timestamp epoch en millisecondes transmis par la carte.', verbose_name='Horodatage carte (ms)')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='etudiants.etudiant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='terminaux.terminal')),
            ],
            options={
                'verbose_name': 'Journal de scan',
                'verbose_name_plural': 'Journaux de scan',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['uid'], name='iot_journal_uid_2c7ed4_idx'), models.Index(fields=['cree_le'], name='iot_journal_cree_le_088284_idx')],
            },
        ),
    ]
