# Generated by Django 5.1.4 on 2026-06-16 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('terminaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('montant', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (centimes FCFA)')),
                ('mis_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='Version')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde', to='etudiants.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Solde',
                'verbose_name_plural': 'Soldes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit'), ('remboursement', 'Remboursement')], max_length=15)),
                ('montant', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (centimes FCFA)')),
                ('statut', models.CharField(choices=[('valide', 'Validée'), ('refuse', 'Refusée'), ('suspect', 'Suspecte'), ('annule', 'Annulée')], default='valide', max_length=10)),
                ('score_fraude', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nonce', models.CharField(max_length=64, unique=True, verbose_name='Nonce (anti-rejeu)')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='terminaux.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['etudiant'], name='monetique_t_etudian_9d3304_idx'), models.Index(fields=['terminal'], name='monetique_t_termina_e33eee_idx'), models.Index(fields=['cree_le'], name='monetique_t_cree_le_3925f4_idx'), models.Index(fields=['statut'], name='monetique_t_statut_aca930_idx')],
            },
        ),
    ]
