# Generated by Django 5.1.4 on 2026-06-16 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('code', models.CharField(help_text='Code unique du terminal, ex : RESTO-01.', max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('restaurant', 'Restaurant'), ('reprographie', 'Reprographie'), ('transport', 'Transport'), ('recharge', 'Recharge'), ('controle', 'Contrôle')], max_length=20, verbose_name='Type')),
                ('libelle', models.CharField(blank=True, max_length=100, verbose_name='Libellé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminaux',
                'ordering': ['code'],
            },
        ),
    ]
