# Generated by Django 5.1.4 on 2026-06-16 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('uid_carte', models.CharField(help_text='Identifiant unique de la carte physique, ex : SC-2025-00147.', max_length=20, unique=True, verbose_name='UID de la carte')),
                ('nom_chiffre', models.TextField(verbose_name='Nom (chiffré)')),
                ('prenom_chiffre', models.TextField(verbose_name='Prénom (chiffré)')),
                ('matricule_chiffre', models.TextField(verbose_name='Matricule (chiffré)')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloqué')], default='actif', max_length=10, verbose_name='Statut de la carte')),
                ('certificat_pub', models.TextField(help_text='Certificat de la carte, utilisé pour vérifier les signatures.', verbose_name='Certificat X.509 (PEM)')),
                ('compte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-cree_le'],
            },
        ),
    ]
